### ISSUE TITLE
Help me please! Why do I get this error

### ISSUE THREAD

**Issue by YuvrajSingh01** [tvganesh/cricpy#5]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-cbabbf86c890> in <module>
----> 1 ca.batsmanMovingAverage("kohli.csv",'kohli')

~/.local/lib/python3.6/site-packages/cricpy/analytics.py in batsmanMovingAverage(file, name)
    841     '''
    842     # Compute the moving average of the time series
--> 843     batsman = clean(file)
    844 
    845     # Set figure size

~/.local/lib/python3.6/site-packages/cricpy/analytics.py in clean(batsmanCSV)
   2585     '''
   2586 
-> 2587     df = pd.read_csv(batsmanCSV,dtype=str,na_values=['-'])
   2588 
   2589     a = df['Runs'] != "DNB"

~/.local/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~/.local/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

~/.local/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

~/.local/lib/python3.6/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

~/.local/lib/python3.6/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File kohli.csv does not exist: 'kohli.csv'

**Comment by tvganesh** [comment]
Make sure you give full path to CSV.

**Comment by YuvrajSingh01** [comment]
I still get an error but its a different one

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/matplotlib/axis.py in convert_units(self, x)
   1572         try:
-> 1573             ret = self.converter.convert(x, self.units, self)
   1574         except Exception as e:

~/.local/lib/python3.6/site-packages/matplotlib/dates.py in convert(value, unit, axis)
   1920         """
-> 1921         return date2num(value)
   1922 

~/.local/lib/python3.6/site-packages/matplotlib/dates.py in date2num(d)
    436             return d
--> 437         return _to_ordinalf_np_vectorized(d)
    438 

~/.local/lib/python3.6/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 

~/.local/lib/python3.6/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2160         else:
-> 2161             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   2162 

~/.local/lib/python3.6/site-packages/numpy/lib/function_base.py in _get_ufunc_and_otypes(self, func, args)
   2120             inputs = [arg.flat[0] for arg in args]
-> 2121             outputs = func(*inputs)
   2122 

~/.local/lib/python3.6/site-packages/matplotlib/dates.py in _to_ordinalf(dt)
    221 
--> 222     base = float(dt.toordinal())
    223 

AttributeError: 'numpy.str_' object has no attribute 'toordinal'

The above exception was the direct cause of the following exception:

ConversionError                           Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/.local/lib/python3.6/site-packages/IPython/core/pylabtools.py in (fig)
    252         jpg_formatter.for_type(Figure, lambda fig: print_figure(fig, 'jpg', **kwargs))
    253     if 'svg' in formats:
--> 254         svg_formatter.for_type(Figure, lambda fig: print_figure(fig, 'svg', **kwargs))
    255     if 'pdf' in formats:
    256         pdf_formatter.for_type(Figure, lambda fig: print_figure(fig, 'pdf', **kwargs))

~/.local/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2077                             print_method, dpi=dpi, orientation=orientation),
   2078                         draw_disabled=True)
-> 2079                     self.figure.draw(renderer)
   2080                     bbox_artists = kwargs.pop("bbox_extra_artists", None)
   2081                     bbox_inches = self.figure.get_tightbbox(renderer,

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1734             self.patch.draw(renderer)
   1735             mimage._draw_list_compositing_images(
-> 1736                 renderer, self, artists, self.suppressComposite)
   1737 
   1738             renderer.close_group('figure')

~/.local/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    135     if not_composite or not has_images:
    136         for a in artists:
--> 137             a.draw(renderer)
    138     else:
    139         # Composite any adjacent images together

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2628             renderer.stop_rasterizing()
   2629 
-> 2630         mimage._draw_list_compositing_images(renderer, self, artists)
   2631 
   2632         renderer.close_group('axes')

~/.local/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    135     if not_composite or not has_images:
    136         for a in artists:
--> 137             a.draw(renderer)
    138     else:
    139         # Composite any adjacent images together

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/matplotlib/text.py in draw(self, renderer)
    683 
    684         with _wrap_text(self) as textobj:
--> 685             bbox, info, descent = textobj._get_layout(renderer)
    686             trans = textobj.get_transform()
    687 

~/.local/lib/python3.6/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    276         of a rotated text when necessary.
    277         """
--> 278         key = self.get_prop_tup(renderer=renderer)
    279         if key in self._cached:
    280             return self._cached[key]

~/.local/lib/python3.6/site-packages/matplotlib/text.py in get_prop_tup(self, renderer)
    844         need to know if the text has changed.
    845         """
--> 846         x, y = self.get_unitless_position()
    847         renderer = renderer or self._renderer
    848         return (x, y, self.get_text(), self._color,

~/.local/lib/python3.6/site-packages/matplotlib/text.py in get_unitless_position(self)
    826         # This will get the position with all unit information stripped away.
    827         # This is here for convenience since it is done in several locations.
--> 828         x = float(self.convert_xunits(self._x))
    829         y = float(self.convert_yunits(self._y))
    830         return x, y

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in convert_xunits(self, x)
    176         if ax is None or ax.xaxis is None:
    177             return x
--> 178         return ax.xaxis.convert_units(x)
    179 
    180     def convert_yunits(self, y):

~/.local/lib/python3.6/site-packages/matplotlib/axis.py in convert_units(self, x)
   1574         except Exception as e:
   1575             raise munits.ConversionError('Failed to convert value(s) to axis '
-> 1576                                          f'units: {x!r}') from e
   1577         return ret
   1578 

ConversionError: Failed to convert value(s) to axis units: '2002-01-03'
